/**
 * Chinese province name mapping constants
 * Used for map chart data processing
 * These are data mappings, not UI text
 */

// Province name mapping (simplified name -> standard name)
export const PROVINCE_NAME_MAP: Record<string, string> = {
  'Beijing': 'Beijing',
  'Shanghai': 'Shanghai',
  'Tianjin': 'Tianjin',
  'Chongqing': 'Chongqing',
  'Guangdong': 'Guangdong',
  'Jiangsu': 'Jiangsu',
  'Zhejiang': 'Zhejiang',
  'Shandong': 'Shandong',
  'Sichuan': 'Sichuan',
  'Hubei': 'Hubei',
  'Henan': 'Henan',
  'Hunan': 'Hunan',
  'Anhui': 'Anhui',
  'Fujian': 'Fujian',
  'Jiangxi': 'Jiangxi',
  'Hebei': 'Hebei',
  'Shanxi': 'Shanxi',
  'Inner Mongolia': 'Inner Mongolia Autonomous Region',
  'Liaoning': 'Liaoning',
  'Jilin': 'Jilin',
  'Heilongjiang': 'Heilongjiang',
  'Guangxi': 'Guangxi Zhuang Autonomous Region',
  'Hainan': 'Hainan',
  'Guizhou': 'Guizhou',
  'Yunnan': 'Yunnan',
  'Tibet': 'Tibet Autonomous Region',
  'Shaanxi': 'Shaanxi',
  'Gansu': 'Gansu',
  'Qinghai': 'Qinghai',
  'Ningxia': 'Ningxia Hui Autonomous Region',
  'Xinjiang': 'Xinjiang Uygur Autonomous Region',
  'Taiwan': 'Taiwan',
  'Hong Kong': 'Hong Kong Special Administrative Region',
  'Macau': 'Macau Special Administrative Region'
};

// Chinese province names (for data matching)
export const CHINESE_PROVINCE_NAMES: Record<string, string> = {
  '北京': 'Beijing',
  '上海': 'Shanghai',
  '天津': 'Tianjin',
  '重庆': 'Chongqing',
  '广东': 'Guangdong',
  '江苏': 'Jiangsu',
  '浙江': 'Zhejiang',
  '山东': 'Shandong',
  '四川': 'Sichuan',
  '湖北': 'Hubei',
  '河南': 'Henan',
  '湖南': 'Hunan',
  '安徽': 'Anhui',
  '福建': 'Fujian',
  '江西': 'Jiangxi',
  '河北': 'Hebei',
  '山西': 'Shanxi',
  '内蒙古': 'Inner Mongolia',
  '辽宁': 'Liaoning',
  '吉林': 'Jilin',
  '黑龙江': 'Heilongjiang',
  '广西': 'Guangxi',
  '海南': 'Hainan',
  '贵州': 'Guizhou',
  '云南': 'Yunnan',
  '西藏': 'Tibet',
  '陕西': 'Shaanxi',
  '甘肃': 'Gansu',
  '青海': 'Qinghai',
  '宁夏': 'Ningxia',
  '新疆': 'Xinjiang',
  '台湾': 'Taiwan',
  '香港': 'Hong Kong',
  '澳门': 'Macau'
};

// Standard Chinese province names mapping
export const STANDARD_CHINESE_PROVINCE_NAMES: Record<string, string> = {
  '北京市': 'Beijing',
  '上海市': 'Shanghai',
  '天津市': 'Tianjin',
  '重庆市': 'Chongqing',
  '广东省': 'Guangdong',
  '江苏省': 'Jiangsu',
  '浙江省': 'Zhejiang',
  '山东省': 'Shandong',
  '四川省': 'Sichuan',
  '湖北省': 'Hubei',
  '河南省': 'Henan',
  '湖南省': 'Hunan',
  '安徽省': 'Anhui',
  '福建省': 'Fujian',
  '江西省': 'Jiangxi',
  '河北省': 'Hebei',
  '山西省': 'Shanxi',
  '内蒙古自治区': 'Inner Mongolia',
  '辽宁省': 'Liaoning',
  '吉林省': 'Jilin',
  '黑龙江省': 'Heilongjiang',
  '广西壮族自治区': 'Guangxi',
  '海南省': 'Hainan',
  '贵州省': 'Guizhou',
  '云南省': 'Yunnan',
  '西藏自治区': 'Tibet',
  '陕西省': 'Shaanxi',
  '甘肃省': 'Gansu',
  '青海省': 'Qinghai',
  '宁夏回族自治区': 'Ningxia',
  '新疆维吾尔自治区': 'Xinjiang',
  '台湾省': 'Taiwan',
  '香港特别行政区': 'Hong Kong',
  '澳门特别行政区': 'Macau'
};

